---
- name: Install glusterfs
  apt:
    name: [ 'glusterfs-common' ]
    state: present
    update_cache:     "{{ apt_proxy.update_repo | default(no) }}"
    cache_valid_time: "{{ apt_proxy.update_cache | default(0) }}"
  become: yes

# - name: Install glusterfs-client-package
#   apt:
#     name: [ 'glusterfs-client' ]
#     state: present
#     update_cache:     "{{ apt_proxy.update_repo | default(no) }}"
    cache_valid_time: "{{ apt_proxy.update_cache | default(0) }}"
#   become: yes